# Uncomment the following lines to define your default indexer and rpc urls
indexer_url = "https://your-indexer-url"
rpc_url = "https://your-rpc-url"
masp_indexer_url = "https://your-masp-indexer-url"  # Optional
#localnet_enabled = false
